###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mall-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
swagger:
  base-package: com.mall.member.service
  title: SpringCloud2.x微服务电商项目-会员服务接口